### ISSUE TITLE
configure.ac:8: error: required file 'src/config_gen.h.in' not found

### ISSUE THREAD

**Issue by dk47os3r** [ashegoulding/proone#3]
sh bootstrap.sh               
configure.ac:12: installing './compile'
configure.ac:10: installing './config.guess'
configure.ac:10: installing './config.sub'
configure.ac:9: installing './install-sh'
configure.ac:9: installing './missing'
configure.ac:8: error: required file 'src/config_gen.h.in' not found
src/Makefile.am: installing './depcomp'

**Comment by dxdxdt** [comment]
Introduced in eea0a9fb
Fixed in bd69f1e9afca387f1c143e14d553c42b88aca20b

Pull and run again. Or run `autoheader` before running the script.

Thank you for your contribution.
